Add rviz plugin to start and resume navigation
KBKN-Autonomous-Robotics-Lab/orange_navigation pull request #3
Opened 2023-10-07 13:56 UTC by koki0624

## 概要

- rviz_pluginsのros2への移植

### なぜこのタスクを行うのか

- このリポジトリでブランチを分け、つくばチャレンジに向けたウェイポイントナビゲーション機能のros2バージョンを作ろうと思います。主に使うのは私ではないのでレビューしてもらいつつ進めたいと考えています。よろしくお願いします。

### やったこと

- 手始めに、ナビゲーションの開始と再開をGUIで行うためのrviz2のプラグインを作成しました。

### その他

- ビルドができたらrviz2を起動して、以下の手順で機能の確認をお願いします。
1. 左上の Panels タブから、Add New Panel をクリック
<img width="206" alt="image" src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/assets/88423990/6e5e6f77-93cf-4601-9bc4-3cf817635a8c">

2. StateTriggerPanel をダブルクリック
<img width="290" alt="image" src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/assets/88423990/1310156e-b843-4251-a5d4-9cde367c1530">

3. 左下に表示されるパネル内のボタンをクリックし、rviz2を起動したターミナルに以下のメッセージがでるか確認
<img width="202" alt="image" src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/assets/88423990/349e2d1c-9c55-48b3-b7c7-3f29fab50b52">

```
[INFO] [1696685821.959832447] [state_trigger_panel]: Service call: start waypoints navigation
[INFO] [1696685823.796478754] [state_trigger_panel]: Service call: resume waypoints navigation
```

2023-10-08 00:30 UTC, Alpaca-zip commented
対応ありがとうございます。
今日の夜中には確認します。

2023-10-08 16:08 UTC, Alpaca-zip reviewed
動作確認できました。良いと思います。

以下の設定ファイルでclang-formatをかける作業だけ追加でお願いできますか？
https://github.com/KBKN-Autonomous-Robotics-Lab/ros2-pkg-template/blob/main/.clang-format

2023-10-09 05:14 UTC, koki0624 commented
#4 と編集ファイルが被ったのでこちらにまとめました。変更点は waypoint_manager 内のタイポの修正とテストデータの追加のみなので、rviz_plugins の機能に影響はありません。

2023-10-09 06:16 UTC, Alpaca-zip requested changes
- https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/pull/4 の内容も確認しました。右クリック -> `Add waypoint here`で正しくwaypointを置けていそうだったので問題ないと思います。
- Industrial CIに関しては、clang_format_checkとblack_checkを追加していただいているので良いと思います。clang_tidy_check、pylint_check、build_checkに関しては私が別PRで対応しておきます。
- 一部、ファイルの末尾に改行が入っておらず、禁止マークが出ているのでそちらだけ対応お願いします。

2023-10-09 06:16 UTC, Alpaca-zip commented on .github/workflows/ci.yaml
> +  #       env: ${{matrix.env}}
ファイルの末尾に改行を入れてください。

2023-10-09 06:16 UTC, Alpaca-zip commented on waypoint_manager/test/waypoints.yaml
> +    orientation: {x: -0.0, y: 0.0, z: -0.004310224710037526, w: 0.9999907109383311}
> ファイルの末尾に改行を入れてください。

こちらもお願いします。

2023-10-09 06:19 UTC, Alpaca-zip commented
確認ですが、以下PRはマージせずclose予定ということで大丈夫ですか？
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/pull/4

2023-10-09 06:35 UTC, koki0624 commented
> * [Fix typo in manager_GUI.py and add test files #4](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation/pull/4) の内容も確認しました。右クリック -> `Add waypoint here`で正しくwaypointを置けていそうだったので問題ないと思います。
> * Industrial CIに関しては、clang_format_checkとblack_checkを追加していただいているので良いと思います。clang_tidy_check、pylint_check、build_checkに関しては私が別PRで対応しておきます。
> * 一部、ファイルの末尾に改行が入っておらず、禁止マークが出ているのでそちらだけ対応お願いします。

対応ありがとうございます。



> 確認ですが、以下PRはマージせずclose予定ということで大丈夫ですか？ #4

こちらのブランチをマージしたらcloseする予定です。

2023-10-09 06:41 UTC, Alpaca-zip approved these changes

2023-10-09 06:41 UTC, merged